language: python

python:
- 2.7

install:
- pip install -r requirements.txt
- pip install fabric pytest-django pytest-xdist ijson coveralls coverage
- cd backendfiddle
- python manage.py migrate
- cd ..

script:
- fab coverage
after_success:
  coveralls
